name: Frontend (React.js) workflow - Build and deploy app to S3 bucket

on: 
  push:
    branches:
      - "main"
    paths:
      - "frontend/**"
      - ".github/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "frontend/**"
      - ".github/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node-version: [18.x]
    
    steps:
      - uses: actions/checkout@v3
      - name: Install node modules
        run: npm install
        working-directory: frontend
      - name: Build project
        run: npm run build
        working-directory: frontend
      - name: Deploy to S3 bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
          SOURCE_DIR: 'frontend/build' 


